local FontStyler = {}

function FontStyler:CreateView(parent)
    local f = ForgeMaster.Theme:CreatePanel(parent, "FM_FontStyler")
    f:SetAllPoints()
    local label = f:CreateFontString(nil, "OVERLAY", "GameFontNormalLarge")
    label:SetPoint("TOP", 0, -20)
    label:SetText("Font & String Styler\nPreview and export font code:")
    local preview = f:CreateFontString(nil, "OVERLAY", "GameFontNormalHuge")
    preview:SetPoint("TOP", label, "BOTTOM", 0, -30)
    preview:SetText("Sample Text")
    local slider = CreateFrame("Slider", nil, f, "OptionsSliderTemplate")
    slider:SetPoint("TOP", preview, "BOTTOM", 0, -20)
    slider:SetMinMaxValues(8, 72)
    slider:SetValue(18)
    slider:SetValueStep(1)
    slider:SetWidth(200)
    slider:SetScript("OnValueChanged", function(_, val)
        preview:SetFont("Fonts\\FRIZQT__.TTF", val, "OUTLINE")
        f.ExportCode = string.format("fs:SetFont([[Fonts\\FRIZQT__.TTF]], %d, 'OUTLINE')", val)
    end)
    local exportBtn = CreateFrame("Button", nil, f, "UIPanelButtonTemplate")
    exportBtn:SetSize(120, 25)
    exportBtn:SetText("Copy Code")
    exportBtn:SetPoint("TOP", slider, "BOTTOM", 0, -10)
    exportBtn:SetScript("OnClick", function()
        ForgeMaster:CopyToClipboard(f.ExportCode or "")
    end)
    self.View = f
end

ForgeMaster:RegisterModule("FontStyler", FontStyler)
